name: app_learn_english
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  http: ^0.13.4
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^0.22.0
  scoped_model: ^1.0.1
  image_picker: ^0.8.4
  percent_indicator: ^3.0.1
  table_calendar: ^3.0.2
  provider: ^6.0.0
  animated_text_kit: ^4.2.1
  restart_app: ^1.1.0
  smooth_page_indicator: ^1.0.0+2
  flutter_scale_tap: ^1.0.5
  launch_review: ^3.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #  cupertino_icons: ^1.0.2
  #  flutter_plyr: ^0.0.4
  responsive_framework: ^0.1.4
  fluttertoast: ^8.0.8
  firebase_auth: ^3.1.1
  url_launcher: ^6.0.12
  flutter_facebook_auth: ^3.5.1
  google_sign_in: ^5.1.1
  flutter_webview_plugin: ^0.3.11
  youtube_api: ^1.0.4
  youtube_player_flutter: ^8.0.0
  youtube_player_iframe: ^2.2.2
  carousel_slider: ^4.0.0
  shared_preferences: ^2.0.6
  flutter_calendar_carousel: ^2.0.3
  flutter_tts: ^3.2.2
  transparent_image: ^2.0.0
  highlight_text: ^1.1.0
  speech_to_text: ^5.0.0
  avatar_glow: ^2.0.1
  permission_handler: ^8.1.6
  substring_highlight: ^1.0.33
  webview_flutter: ^3.0.2
  text_to_speech: ^0.2.3
  show_more_text_popup: ^0.3.0
  tutorial_coach_mark: ^1.2.3

  # check status internet
  connectivity_plus: ^1.1.0
  internet_connection_checker: ^0.0.1+2
  overlay_support: ^1.2.1
  firebase_messaging: ^10.0.7
  firebase_core: ^1.6.0
  cloud_firestore_web: ^2.4.1
  flutter_native_timezone: ^2.0.0
  flutter_local_notifications: ^8.2.0
  rxdart: ^0.27.2
  modal_bottom_sheet: ^2.0.0
  google_mobile_ads: ^0.13.5
  share_plus: ^3.0.4
  random_string: ^2.3.1
  uni_links: ^0.5.1
  audioplayers: ^0.20.1
  file: ^6.1.2
  path: ^1.8.0
  record: ^3.0.0
  tiengviet: ^0.5.0
  flutter_launcher_icons: ^0.9.2
  in_app_purchase: ^1.0.9
  sign_in_with_apple: ^3.3.0
  swipe_to: ^0.0.1+8
  miniplayer: ^1.0.1
  just_audio: ^0.9.18
  flutter_switch: ^0.3.2
  timer_count_down: ^2.2.1
  confetti: ^0.6.0
  platform_device_id: ^1.0.1
  crypto: ^3.0.1
  flutter_gifimage: ^1.0.1
  web_socket_channel: ^2.1.0
  syncfusion_flutter_gauges: ^18.4.49
  devicelocale: ^0.5.0
  flutter_slidable: ^1.2.0
  onesignal_flutter: ^3.0.0
  just_the_tooltip: ^0.0.11+2
  toggle_switch: ^2.0.1
  persistent_bottom_nav_bar: ^4.0.2
  cached_network_image: ^3.2.0
  flutter_webrtc: ^0.6.6
  cloud_firestore: ^2.5.1
  lottie: ^1.2.2
  device_info_plus: ^3.2.4
  date_field: ^3.0.1
  package_info_plus: ^1.4.2
  auto_size_text: ^3.0.0
  animated_splash_screen: ^1.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: false
  ios: true
  image_path_ios: "assets/icon_logo/ios/iTunesArtwork@3x.png"
  image_path_android: "assets/icon_logo/android/ic_launcher-web.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/cake/
    - assets/startPage/
    - assets/sub_chanel/
    - assets/flags/
    - assets/controll_touch/
    - assets/Target/
    - assets/Profile/
    - assets/icons-svg/
    - assets/linh_vat/
    - assets/iconbuttonsvg-2/
    - assets/icon_new/
    - assets/icon-2/
    - assets/quiz/
    - assets/audio/
    - assets/icon_logo/
    - assets/speak/
    - assets/new_ui/home/
    - assets/new_ui/more/
    - assets/new_ui/first_screen_app/
    - assets/new_ui/animation_lottie/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Bold.ttf
    - family: Tahoma
      fonts:
        - asset: assets/fonts/Tahoma/Tahoma-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-bold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
