class TalkVideoHistory {
  int id;
  int catId2;
  int catId;
  int catId3;
  int catId4;
  int catId5;
  String picture;
  String linkOrigin;
  int totalLike;
  int totalSub;
  String name;
  String nameVi;
  String nameZh;
  String nameJa;
  String nameHi;
  String nameEs;
  String nameRu;
  String author;
  String createdtime;
  String updatetime;
  bool isVip;
  bool type;
  int catelogId;
  int status;
  String nameTr;
  String nameTh;
  String nameMy;
  String nameSa;
  String nameFr;
  String nameIt;
  String nameDe;
  String nameKo;
  String nameZhHantTw;
  String nameGr;
  String nameBr;
  String nameSl;
  String nameSk;
  String nameId;
  String namePt;
  String nameAr;
  String nameMs;

  TalkVideoHistory({
    required this.id,
    required this.catId2,
    required this.catId,
    required this.catId3,
    required this.catId4,
    required this.catId5,
    required this.picture,
    required this.linkOrigin,
    required this.totalLike,
    required this.totalSub,
    required this.name,
    required this.nameVi,
    required this.nameZh,
    required this.nameJa,
    required this.nameHi,
    required this.nameEs,
    required this.nameRu,
    required this.author,
    required this.createdtime,
    required this.updatetime,
    required this.isVip,
    required this.type,
    required this.catelogId,
    required this.status,
    required this.nameTr,
    required this.nameTh,
    required this.nameMy,
    required this.nameSa,
    required this.nameFr,
    required this.nameIt,
    required this.nameDe,
    required this.nameKo,
    required this.nameZhHantTw,
    required this.nameGr,
    required this.nameBr,
    required this.nameSl,
    required this.nameSk,
    required this.nameId,
    required this.namePt,
    required this.nameAr,
    required this.nameMs,
  });

  factory TalkVideoHistory.fromJson(Map<String, dynamic> json) {
    return TalkVideoHistory(
      id: json['id'],
      catId2: json['catId_2'],
      catId: json['catId'],
      catId3: json['catId_3'],
      catId4: json['catId_4'],
      catId5: json['catId_5'],
      picture: json['picture'],
      linkOrigin: json['link_origin'],
      totalLike: json['totalLike'],
      totalSub: json['totalSub'],
      name: json['name'],
      nameVi: json['name_vi'],
      nameZh: json['name_zh'],
      nameJa: json['name_ja'],
      nameHi: json['name_hi'],
      nameEs: json['name_es'],
      nameRu: json['name_ru'],
      author: json['author'],
      createdtime: json['createdtime'],
      updatetime: json['updatetime'],
      isVip: json['isVip'],
      type: json['type'],
      catelogId: json['catelog_id'],
      status: json['status'],
      nameTr: json['name_tr'],
      nameTh: json['name_th'],
      nameMy: json['name_my'],
      nameSa: json['name_sa'],
      nameFr: json['name_fr'],
      nameIt: json['name_it'],
      nameDe: json['name_de'],
      nameKo: json['name_ko'],
      nameZhHantTw: json['name_zh_hant_tw'],
      nameGr: json['name_gr'],
      nameBr: json['name_br'],
      nameSl: json['name_sl'],
      nameSk: json['name_sk'],
      nameId: json['name_id'],
      namePt: json['name_pt'],
      nameAr: json['name_ar'],
      nameMs: json['name_ms'],
    );
  }

  Map<String, dynamic> toJson() => {
        'id': this.id,
        'catId_2': this.catId2,
        'catId': this.catId,
        'catId_3': this.catId3,
        'catId_4': this.catId4,
        'catId_5': this.catId5,
        'picture': this.picture,
        'link_origin': this.linkOrigin,
        'totalLike': this.totalLike,
        'totalSub': this.totalSub,
        'name': this.name,
        'name_vi': this.nameVi,
        'name_zh': this.nameZh,
        'name_ja': this.nameJa,
        'name_hi': this.nameHi,
        'name_es': this.nameEs,
        'name_ru': this.nameRu,
        'author': this.author,
        'createdtime': this.createdtime,
        'updatetime': this.updatetime,
        'isVip': this.isVip,
        'type': this.type,
        'catelog_id': this.catelogId,
        'status': this.status,
        'name_tr': this.nameTr,
        'name_th': this.nameTh,
        'name_my': this.nameMy,
        'name_sa': this.nameSa,
        'name_fr': this.nameFr,
        'name_it': this.nameIt,
        'name_de': this.nameDe,
        'name_ko': this.nameKo,
        'name_zh_hant_tw': this.nameZhHantTw,
        'name_gr': this.nameGr,
        'name_br': this.nameBr,
        'name_sl': this.nameSl,
        'name_sk': this.nameSk,
        'name_id': this.nameId,
        'name_pt': this.namePt,
        'name_ar': this.nameAr,
        'name_ms': this.nameMs,
      };
}
